name: Playwright BDD CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Cucumber tests (headless)
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}
          BROWSER: chromium
          HEADLESS: true
        run: npm test

      - name: Generate advanced HTML report
        if: always()
        run: npm run report:advanced

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: reports/html-report
